version: '2'

services:
#  search:
#    build: ./elasticsearch
#    container_name: search
#    expose:
#      - "9200"
#      - "9300"
  node-admin:
    build: ./node-admin
    container_name: node-admin
    expose:
      - "8080"
    volumes:
      - ./node-admin:/app
      - ./files:/app/files
#    depends_on:
#        - search
#        - redis
    links:
#      - search
      - redis
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "81:81"
    volumes:
      - ./nginx/static:/usr/share/nginx/html
      - ./files:/usr/share/nginx/html/files
    depends_on:
      - redis
      - node-admin
#      - search
    links:
      - node-admin
  redis:
    image: redis
    expose:
      - "6379"
