version: '2'

services:
  search:
    build: ./search
    container_name: search
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - ./files/index:/go/src/app/indexes
  node-admin:
    build: ./node-admin
    container_name: node-admin
    ports:
      - "8081:8081"
    expose:
      - "8081"
    volumes:
      - ./node-admin:/app
      - ./files:/app/files
#    depends_on:
#        - search
#        - redis
    links:
      - search
      - redis
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/static:/usr/share/nginx/html
      - ./files:/usr/share/nginx/html/files
    depends_on:
      - redis
      - node-admin
#      - search
    links:
      - node-admin
  redis:
    image: redis
    container_name: redis
    expose:
      - "6379"
