#!/bin/bash



#Input file: "icc.ibc.2012.pdf"
#Output file: "icc.ibc.2012_54.pdf"
#Number of pages in inputfile: 794
#More threads than pages. Using 1 threads instead.
#Processing page 54.
#identify -format "%w\n%h\n"  "icc.ibc.2012.pdf[53]"
#convert  -type Bilevel  -density 300x300 "icc.ibc.2012.pdf[53]" /tmp/pdfsandwichce86e3.pbm
#unpaper --overwrite  --no-grayfilter --layout none /tmp/pdfsandwichce86e3.pbm /tmp/pdfsandwich02639f_unpaper.pbm
#Processing sheet #1: /tmp/pdfsandwichce86e3.pbm -> /tmp/pdfsandwich02639f_unpaper.pbm
#tesseract /tmp/pdfsandwich02639f_unpaper.pbm /tmp/pdfsandwich3ce093  -l eng pdf
#Tesseract Open Source OCR Engine v3.03 with Leptonica
#gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dDEVICEWIDTHPOINTS=612 -dDEVICEHEIGHTPOINTS=792 -dPDFFitPage -o /tmp/pdfsandwich4b84b0.pdf /tmp/pdfsandwich3ce093.pdf
#GPL Ghostscript 9.10: Missing glyph CID=0, glyph=0079 in the font GlyphLessFont . The output PDF may fail with some viewers.
#OCR done. Writing "icc.ibc.2012_54.pdf"
#gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile="icc.ibc.2012_54.pdf" /tmp/pdfsandwich4b84b0.pdf


dpi=`identify -format "%w\n%h\n"  "icc.ibc.2012.pdf[53]"`
echo $dpi : '(\/d/n)\'

hdpi=$((dpi[0]))
vdpi=$((dpi[1]))
echo "DPI: $dpi"
echo "DPI: $hdpi x $vdpi"
